services:
  ezmoney-pg:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: ezmoney
      POSTGRES_PASSWORD: ezmoney
      POSTGRES_DB: ezmoney
    ports:
      - "5432:5432"
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
