name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: bitnami/postgresql
        ports: ["5432:5432"]
        env:
          POSTGRESQL_USERNAME: ezmoney
          POSTGRESQL_PASSWORD: ezmoney
          POSTGRESQL_DATABASE: ezmoney
    env:
      JWT_SECRET: testing
      DATABASE_URL: "postgresql://plaseg:plaseg@localhost:5432/plaseg?schema=public"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm migrate
      - run: pnpm generate
      - run: pnpm build
      - run: pnpm test:e2e
